version: '3.8'
services:
  #PHP Setup
  php:
    build:
      context: .
      target: php 
      args:
        - APP_ENV= ${APP_ENV}
    environment:
      - APP_ENV= ${APP_ENV}
      - CONTAINER_ROLE= app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - backend

  # Database Server
  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABSE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

volumes:
  db-data: ~


networks:
    backend:
      driver: bridge

